# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
import platform
from functools import reduce

import time
import sys

if sys.platform == 'win32':
    default_timer = time.perf_counter
else:
    default_timer = time.time

start = default_timer()

print("Using: " + platform.python_version())

sum = 2
terms = [1, 2]


def nextTerm(terms):
    return reduce((lambda x, y: x+y), terms)


limit = 4000000
while terms[1] < limit:
    term = nextTerm(terms)
    if(term % 2 == 0):
        sum += term

    terms.pop(0)
    terms.append(term)

end = default_timer()
elapsed = (end - start) * 1000 * 1000
print("{:.2f}".format(elapsed) + " ns")
print("The term sum is: " + str(sum))
