# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

import platform
from functools import reduce
import time
import sys

if sys.platform == 'win32':
    default_timer = time.perf_counter
else:
    default_timer = time.time

start = default_timer()

print("Using: " + platform.python_version())

sum = 0
term_one = 1
term_two = 2

limit = 4000000
while term_two < limit:
    sum += term_two
    n1_term = term_one + term_two
    n2_term = n1_term + term_two
    n3_term = n2_term + n1_term

    term_one = n2_term
    term_two = n3_term

end = default_timer()
elapsed = (end - start) * 1000 * 1000
print("{:.2f}".format(elapsed) + " ns")
print("The term sum is: " + str(sum))
